---
- name: elementer til am servere
  hosts: all
  become: true
  pre_tasks:
  - name: Enable codeready-builder repo
    command: >
      subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
    register: codeready_repo_result
    changed_when: "'enabled' in codeready_repo_result.stdout"
    failed_when: codeready_repo_result.rc != 0 and 'is already enabled' not in codeready_repo_result.stdout

  - name: Clean yum metadata
    command: yum clean all

  - name: Refresh yum metadata
    command: yum makecache

  - name: Run yum update on all servers to ensure they are up to date
    yum:
      name: '*'
      state: latest
      
- hosts: prod_id_servers:udv_id_servers
  become: true
  tasks:
  - name: firewall rules for id servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 443/tcp
      - 524/tcp
      - 1443/tcp
      - 7801/tcp
      - 8443/tcp
      - 9968/tcp
      
- hosts: prod_admin_servers:udv_admin_servers
  become: true
  tasks:
  - name: firewall rules for admin servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 524/tcp
      - 636/tcp
      - 705/tcp
      - 1290/tcp
      - 8030/tcp
      - 8443/tcp
      - 8444/tcp
      - 9968/tcp
      
- hosts: prod_gw_servers:udv_gw_servers
  become: true
  tasks:
  - name: firewall rules for gw servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 443/tcp
      - 524/tcp
      - 1099/tcp
      - 1443/tcp
      - 7801/tcp
      - 9968/tcp
      
- hosts: prod_id_servers:udv_id_servers
  become: true
  tasks:
  - name: firewall rules for odb servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 1521/tcp
      
- hosts: prod_sspr_servers:udv_sspr_servers
  become: true
  tasks:
  - name: firewall rules for sspr servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 80/tcp
      - 443/tcp
      
- hosts: prod_edir_servers:udv_edir_servers
  become: true
  tasks:
  - name: firewall rules for edir servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 524/tcp
      - 636/tcp
      - 8030/tcp
      - 8443/tcp
      
- hosts: aa_fwrules_targets
  become: true
  tasks:
  - name: firewall rules for aa servers
    firewalld:
      port: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - 22/tcp
      - 80/tcp
      - 443/tcp
      - 8080/tcp
      - 5432/tcp
      - 9200/tcp
      - 9300/tcp
 
      
